FROM python:3.9.9-alpine



#on vient definir un repertoir de travail, un default path
WORKDIR /app/

# on vient copier le contenu de From_Path → To_Path /app/
COPY . .
# on vient ecrir dans le fichier favorites_cakes.txt
#RUN echo "Cookies and cheesecakes are my favorites" > favorites_cakes.txt

# On lance l'execution du script app.py
CMD python app.py

